services:
  - type: web
    name: pixbot-lite-system
    env: node
    plan: free
    buildCommand: npm install --force && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
