services:
  - type: web
    name: pixbot-lite-system
    env: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: DATABASE_URL
        value: mysql://2KmX4wgEXs3QV3p.root:enhteRt3raZMyZMM@gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?ssl={"rejectUnauthorized":true}
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
