CREATE DATABASE IF NOT EXISTS bot_financeiro;
USE bot_financeiro;

CREATE TABLE IF NOT EXISTS clientAccounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  telegramId VARCHAR(64),
  telegramName VARCHAR(255),
  isActive BOOLEAN DEFAULT TRUE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clientId INT NOT NULL,
  balance DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  totalDeposited DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  totalWithdrawn DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  walletId INT NOT NULL,
  clientId INT NOT NULL,
  type ENUM('deposit', 'withdrawal') NOT NULL,
  status ENUM('pending', 'approved', 'completed', 'rejected', 'failed') DEFAULT 'pending' NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  fee DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  netAmount DECIMAL(15, 2) NOT NULL,
  pixKey VARCHAR(255),
  pixKeyType VARCHAR(32),
  qrCode TEXT,
  copyPaste TEXT,
  expiresAt TIMESTAMP NULL,
  adminNote TEXT,
  approvedAt TIMESTAMP NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS affiliates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clientId INT NOT NULL UNIQUE,
  referralCode VARCHAR(20) NOT NULL UNIQUE,
  totalReferrals INT DEFAULT 0 NOT NULL,
  totalCommission DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS referrals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  affiliateId INT NOT NULL,
  referredClientId INT NOT NULL UNIQUE,
  commissionEarned DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS adminWallet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  balance DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  totalFeesEarned DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(64) NOT NULL UNIQUE,
  value TEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- Inserir configurações iniciais
INSERT IGNORE INTO settings (`key`, value) VALUES 
('deposit_fee_percent', '20'),
('withdrawal_fee_fixed', '3.00'),
('min_withdrawal', '20.00'),
('min_deposit', '10.00'),
('max_daily', '10000.00');

-- Inserir carteira admin inicial
INSERT IGNORE INTO adminWallet (id, balance, totalFeesEarned) VALUES (1, 0.00, 0.00);
